### ISSUE TITLE
Incorrect mapping: pending change did not remove...

### ISSUE THREAD

**Issue by scriptacus** [groboclown/p4ic4idea#100]
[   9840]   WARN - ync.FileActionsServerCacheSync - Incorrect mapping: pending change did not remove //depot/somefile.txt -> c:\depot\somefile.txt@0 add_edit_file

I'm seeing this kind of error a lot.  All of the files in these instances have the @0 ending.

**Comment by groboclown** [comment]
This has to do with the internal caching of the pending requests mapping to the pending set of changes.  The current implementation seems to be allowing some inconsistency between the two.  I've been looking at an alternative approach that might help prevent this problem.

**Comment by groboclown** [comment]
The issue was a bad hash set / hash code usage.  Hopefully the fix I've put in place will keep this from happening again, but I'll keep a look out to see if some other state can cause this.
