### ISSUE TITLE
automatic add to VCS option fails

### ISSUE THREAD

**Issue by scriptacus** [groboclown/p4ic4idea#102]
The following fails in my case:

1) In an open file, choose Refactor->Copy
2) Give the new file a name
3) When the editor prompts to add to perforce, say OK

At this point the file will be shown in your changelist
4) Click "Refresh"
At this point, the file is gone, as it was never actually added to perforce in the first place.
Adding the file manually via the P4 menu works fine.

**Comment by groboclown** [comment]
This should be fixed in the upcoming 0.7.14 release.

**Comment by groboclown** [comment]
FYI - this issue was due to incorrect logic when seeing that the added file came from a copy, rather than as a new file.
