### ISSUE TITLE
Plugin keeps asking for password.

### ISSUE THREAD

**Issue by kcwill2** [groboclown/p4ic4idea#107]
I type in a valid password and everything is fine for a while, but eventually I am prompted for the password again. This happens every few minutes. IDEA version is 15.0.4, plugin version is 0.7.6

**Comment by groboclown** [comment]
Thanks for the bug report.  This is the result of #105, and I've been trying to crack the problem for several weeks.  Today, I found part of the problem in the implementation, with a work-around (not a real fix).
