### ISSUE TITLE
Critical: project not loading after 0.7.7 upgrade

### ISSUE THREAD

**Issue by Pollizzio** [groboclown/p4ic4idea#110]
With plugin 0.7.7 installed and activated on Android studio 1.5.1 my project does not load anymore: infinite waiting dialog on root folder and no file showed. When disable\uninstall the plugin the issue disappears.
I'm using this plugin successfully since months.

Thanks

**Comment by groboclown** [comment]
Thanks for the bug report.  This looks to be tightly related to the issues other people are seeing with the constant unauthorized return code from the server.

**Comment by groboclown** [comment]
I've tracked this down to an issue with how the PasswordSafe utility in 1.5 handles thread safety - it seems like it is different than with other builds.  It used to work fine when called within the EDT, but that doesn't seem to be the case anymore.  I should have a fix out soon.

**Comment by groboclown** [comment]
This is going out in the 0.7.8 release.

**Comment by jkoehring** [comment]
I just installed the 0.7.9 release of the plugin in to Android Studio 1.5.1 and the issue I reported (#112) still exists. I have attached a log file showing the installation of the plugin and the results thereafter. It looks to me like there is a Java class file format version incompatibility issue. Thank you for looking at this again.
[idea.zip](https://github.com/groboclown/p4ic4idea/files/186956/idea.zip)

**Comment by groboclown** [comment]
This particular issue also relates to #113.  Looks like the plugin classloader doesn't act like most classloaders.  This one wraps the LinkageError errors with a PluginException.

I'm not able to reproduce this (my Android Studio installs are all starting up in jre 8).  So hopefully this will actually fix it this time.  This fix should come out shortly.
