### ISSUE TITLE
Plugin does not seem to be compatible with Android Studio 1.5.1

### ISSUE THREAD

**Issue by jkoehring** [groboclown/p4ic4idea#112]

**Comment by jkoehring** [comment]
Oops - accidentally created the issue with no description. Here it is:

The latest version of the plugin (0.7.7) does not seem to be compatible with Android Studio 1.5.1. After installing the plugin I open File => Settings and then select Version Control => Perforce and nothing is displayed in the right-hand portion of the dialog. I have attached a section of my idea.log file containing some exceptions associated with the plugin.
[redacted-idea.zip](https://github.com/groboclown/p4ic4idea/files/183251/redacted-idea.zip)

**Comment by groboclown** [comment]
Thanks for the bug report.  This is already reported in #110, but you included some very nice logging information.

I've tracked this down to an issue with how the PasswordSafe utility in 1.5 handles thread safety - it seems like it is different than with other builds.  It used to work fine when called within the EDT, but that doesn't seem to be the case anymore.  I should have a fix out soon.
