### ISSUE TITLE
0.7.14 version not compatible with Android Studio 2.1

### ISSUE THREAD

**Issue by zhouziyang** [groboclown/p4ic4idea#119]
I installed 0.7.14 version, but it seems not compatible with Android Studio 2.1. I have restart Android Studio after plugin installed. Also, I can't see in Preference -> Version Control settings panel, and perforce not shown up while enable Version Control for a specific project.

**Comment by groboclown** [comment]
Thanks for the bug report.  I wasn't aware that the new version of Android Studio was out.  I'll take a look and see what's going on.

**Comment by groboclown** [comment]
I installed Android Studio 2.1, updated the perforce plugin, and I'm not seeing an issue with it loading.  The Perforce connection status icon isn't showing up in the status bar, but I see the correct version control panel and the Perforce option in the Version Control panel of the settings.

Could you look at your IDE logs and see if you see an exception that looks related to the plugin?  You can find your IDE log from the **Help** menu, then **Show Log in Explorer** (for Windows; I don't know what it says for Linux or Mac versions).

**Comment by zhouziyang** [comment]
I reinstall the plugin, and it worked fine! I'm not sure what is going wrong. Thanks for your support!

**Comment by groboclown** [comment]
You're welcome.  Feel free to open more bug reports if you find them!
