### ISSUE TITLE
Network lag causes the WebStorm UI to lock up when P4 is Online

### ISSUE THREAD

**Issue by gridlined** [groboclown/p4ic4idea#120]
I haven't seen any errors specifically related to this, but when I switch P4 to offline mode the issue goes away. While online, particularly when working over VPN, there are regular and fairly consistent periods in which the IDE becomes totally unresponsive.

These lags usually occur after I've left a file alone for a few minutes and then come back to make an edit. As soon as the first keypress occurs, the IDE seems to continue to register additional changes but they are sort of queued up while some other process is completing. My expectation is, based on the fact that this doesn't happen while in offline mode, that the P4 plugin is determining the status of the local file as compared to the one on the server.

I am seeing this issue on version 0.7.14.

**Comment by groboclown** [comment]
This is great feedback.

What you're seeing is indeed what's going on - with each action, while in online mode, the plugin queues the requests to send to the server.  Some requests must return immediately, though (queries, specifically).

The IDE, though, expects the file to be writable when the edit action finishes.  By default, the plugin will respect this by waiting until the Perforce command to open the file for edit returns (there's some caching that helps prevent this, but it's limited).

In the user options in the plugin setup, you should see a flag to turn on or off the open for edit in a background thread.  When editing is done in a background thread, the plugin will change the file to writable outside of a Perforce request, and move the open-for-edit into a background thread.

Changing this flag could help with your performance problem.  Let me know if this helps, or if you continue to see issues with it.

**Comment by gridlined** [comment]
I actually already had that checkbox checked. However, I also noticed I had checked the option for "Edit without checkout status compares with server version", which specifically notes that it may cause performance issues. I've unchecked that and will monitor. I'll update by the end of the day with notes as to how my issue is affected by removing that flag.

**Comment by gridlined** [comment]
I'm still having issues. I actually noticed this morning that the IDE completely locked when I tried editing and was set to offline mode. When in offline mode I would expect the IDE to unlock files and perform edits without any concern for the P4 status of the file. Later, when I go online, though, I would expect the IDE to check and update the status of the files that were touched (add/edit/delete) appropriately.

**Webstorm version**
<img width="642" alt="screen shot 2016-05-17 at 6 52 36 am" src="https://cloud.githubusercontent.com/assets/3723878/15324668/46fe7702-1bfc-11e6-9a48-84c8d97f5f79.png">

**Plugin version**
<img width="292" alt="screen shot 2016-05-17 at 6 54 27 am" src="https://cloud.githubusercontent.com/assets/3723878/15324671/47084b2e-1bfc-11e6-8c2f-cc4ccaaeb510.png">

**Perforce user preferences**
<img width="463" alt="screen shot 2016-05-17 at 6 53 58 am" src="https://cloud.githubusercontent.com/assets/3723878/15324672/470d830a-1bfc-11e6-88c7-07b42196ac30.png">

**Comment by groboclown** [comment]
Thanks for the great information.  This should help me get an idea of where the issue is occurring.

I've encountered some areas that are causing some major hang ups in the UI around this.  It may or may not be related, though.  In the case I was seeing it, it came when connecting to an SSL enabled server.

Another place you can get more information if you see this happening again is by looking at the thread directories in the IDE log directory.  They are created when the UI thread takes a long time to respond, and shows a snapshot of the thread stack traces.  If you could find one of those files, and paste in the threads that include the "net.groboclown" package, that would also help me make sure I'm on the right path.

**Comment by groboclown** [comment]
I think I found the issue.

It's not with the Perforce code exactly.  It's not hanging up the UI thread explicitly.  However, it does capture a read or write lock on the IDE which can interfere with the UI.  The right solution here is a better mechanism for knowing the right situation to lock on a Perforce request.  Unfortunately, this is non-trivial.

**Comment by groboclown** [comment]
I rewrote much of the synchronization code to now no longer lock the application-wide read state when the P4 actions happen.  This should help minimize the cases where this occurs.
