### ISSUE TITLE
Set proper Perforce Application name and version

### ISSUE THREAD

**Issue by staffanf** [groboclown/p4ic4idea#122]
I'm using `p4 monitor -ael` to check for for long running client connections.
Currently this plugins identifies it self as something like "IntelliJ Perforce Community Plugin connection 0/1".
p4v and other p4 clients typically use identifier without spaces to allow for better command line usage when e.g. sorting by time column.
Also there is no updated version in the string.
A typical p4v application name would be `P4V/NTX64/2015.2/1312139/v79`.
Suggestion for this plugin `intellij-perforce-community-plugin-connection0/0.7.15`  or something like that.
Unsure if there is an "official" naming policy.

This seems to be handled in "plugin/src/net/groboclown/idea/p4ic/server/ConnectionHandler.java"

**Comment by groboclown** [comment]
Thanks for the report.  This has been on the list for a while, and I've wondered about the implication about some monitors.
