### ISSUE TITLE
Error message "<file> corrupted during transfer" on commit

### ISSUE THREAD

**Issue by jimkeir** [groboclown/p4ic4idea#123]
On each commit, the following error appears:

`Error://depot/path/to/file corrupted during transfer 098DB874817FFD82AD12B57FC9412FAA0000000000000000000000000000000 vs 098DB874817FFD82AD12B57FC9412FAA (error code 7633: severity 3, ref 34-465)`

Note that the only difference is that the first digest is 0-padded. The contents of the file are fine, I can commit the changelist from P4V perfectly. It appears it's just a string compare problem in the plugin. Only thing that may be causing an issue is that I'm using a 64-bit OS and Java installation.

**Comment by groboclown** [comment]
This looks like an issue with the underlying p4 java API.  Do you have a stack trace to accompany this?  It should be in your IDE log (the "Help" menu should have an item that quickly locates the file).

**Comment by jimkeir** [comment]
Thanks for the reply. No stack trace that I can see. I've copied/pasted a few lines around the "corrupted" reference, if you need more I can upload the entire thing.

[idealog.txt](https://github.com/groboclown/p4ic4idea/files/309379/idealog.txt)

There are a couple of stack traces in the full file - I think there's the whole history of the western hemisphere since the flood in there - but not related to this.

**Comment by jimkeir** [comment]
A bit more info: This is in Android Studio 2.1 using the plugin 0.7.14 . As far as I can tell, it's using the bundled p4ic4idea.p4java.jar, which contains classes dated 05/04/2016 .

**Comment by MalcolmEvershed** [comment]
I am also encountering this same error, though it only happens about 10-20% of the time.

`idea.log` shows:

`2016-06-12 20:12:12,123 [12345678]   INFO - c.v2.file.P4CheckinEnvironment - Errors: [com.intellij.openapi.vcs.VcsException: //CLIENTNAME/path/Filename.java corrupted during transfer <hexstring>0000000000000000000000000000000 vs <hexstring> (error code 7633: severity 3, ref 34-465), com.intellij.openapi.vcs.VcsException: Some file(s) could not be transferred from client. (error code 7219: severity 3, ref 34-51)] `

p4 info: `P4D/NTX64/2016.1/1396108 (2016/06/03)`
Android Studio 2.1.2
Plugin 0.7.14
x64 everything

Thanks.

**Comment by groboclown** [comment]
This is coming from deep within the p4 java API.

Apparently, the string with the line of "0"s is the server's version of the digest, and the one without it is the locally generated digest.  However, this appears to be a feature introduced in the 10.2 version of the Perforce server.

The local version is explicitly set to be exactly 32 characters, whereas the server version is used as-is.  It looks like in the newest version of the server, there are situations where it can send 64 character digests.

There are some circumstances where the local version of the digest is used if the server's version can't be found, but in those cases this issue won't be seen.

I'm going to investigate the latest version of the p4 java API that Perforce shipped, and see if that includes a fix for this.

**Comment by groboclown** [comment]
I think I found the issue.  It looks to be a bad patch for the p4 java API.  I've brought in the 15.2 release of the P4 Java API, and I'm testing it out now.
