### ISSUE TITLE
Local Changes view shows submitted change

### ISSUE THREAD

**Issue by MalcolmEvershed** [groboclown/p4ic4idea#124]
After hitting the error in #123, I used P4V to submit the change, but the `Local Changes` view in the plugin still shows the changelist (just the title/first-line). Selecting `Refresh` or switching online->offline->online doesn't change the view. Right-clicking the changelist and choosing `Delete Changelist` works.

**Comment by groboclown** [comment]
This could happen if there were pending changes not yet committed to the server.  The biggest issue with this is when pending commits fail, they seem to go into a limbo.

**Comment by groboclown** [comment]
I think I found the fix for this.  It was a bad hash set.  The next release should have a fix for this.
