### ISSUE TITLE
Deleting files in IDEA does not mark for delete

### ISSUE THREAD

**Issue by novaterata** [groboclown/p4ic4idea#126]
I have a multi-project Gradle 2.14 project in IDEA 2016.2. If I delete a file in the IDEA Project browser, the file is not marked for delete in P4. I have to find the file in the P4 depot view and delete it manually.

**Comment by groboclown** [comment]
I think I finally figured out the issue to this long-standing problem.  IDEA sends a message to first open the file for edit, before the delete request is made.  Essentially, the mix of edit + delete can cause the plugin to assume that the plugin is in the wrong state, and it does nothing.

The right answer, it seems, is for the "edit" request to do nothing if the file is already opened in a changelist, and for the delete to revert the file if it is already opened.

**Comment by novaterata** [comment]
Awesome!

**Comment by novaterata** [comment]
Sorry, I'm still unable to delete files. They immediately come back.

**Comment by novaterata** [comment]
@groboclown Please re-open this it's not fixed for me. I still have to manually delete files from P4V. Files moved with Refactor / Move also have to be manually deleted

**Comment by groboclown** [comment]
Well, nuts.  I guess there's another issue lurking in there around this.  Thanks for your patience with this issue.

**Comment by novaterata** [comment]
@groboclown Thanks for this plugin! So, this happens when:
I delete a file that has not been checked out or has been checked out by typing the delete key or selecting Delete from the menu.
It does not currently happen when I rename a file or when I Move files or packages, but I have had it leave behind the original files in the past, so I'm not sure how to reproduce that.

**Comment by groboclown** [comment]
I'm finally seeing this issue again.  Once I finish up the 0.8.0 rc2, I'll investigate this, one more time.

**Comment by groboclown** [comment]
Turned out to be trivial - the wrong flag was passed into the P4 delete API call.  This fix will be in the 0.8.0-rc2 release.

**Comment by groboclown** [comment]
Fix is in https://github.com/groboclown/p4ic4idea/releases/tag/0.8.0-rc2

**Comment by groboclown** [comment]
Fixed in 0.8.0
