### ISSUE TITLE
Automatic removing of submitted change list

### ISSUE THREAD

**Issue by zelig81** [groboclown/p4ic4idea#135]
Hi!
I'm using PyCharm 2016.2.3 and Perforce IDEA Community integration plugin of version 0.7.18 on Windows 8.1. 
First of all thank you very much for this plugin - it is extremely helpful.

I found some issue:
when submitting some change list, it does not go to be removed from the list (even after refreshing). 

Thank you,
Ilya

**Comment by groboclown** [comment]
There are several lingering issues around change lists, mostly around refreshing them.

I think you're seeing the one where, after submitting the change list, the IDE-backed changelist still exists.  You should notice that there isn't a changelist version number associated with the old one.  Right now, you'll have to manually remove it.

Perhaps I'll add in a user option to remove the IDE-backed changelist after submitting.

**Comment by groboclown** [comment]
In the current versions of IntelliJ, the IDE itself will prompt you to remove the changelist after the submission.  If you refresh the changelist list after submitting the changelist from outside the IDE, the IDE's changelist will no longer have the reference to the P4 changelist.

From what I can tell, the IDE should be controlling the removal of the changelists.  One situation that can arise is the user putting files into a changelist that aren't under the control of Perforce (the VCS root is a child of the project root).  In this case, we don't want the Perforce plugin removing the IDE local changelist.

**Comment by groboclown** [comment]
Now that I think more about this issue, the solution could be:

>> If the IDE local changelist was mapped to a Perforce changelist, but the Perforce changelist is now gone, and the IDE local changelist is empty, then remove the IDE local changelist.

That should work.  For those who **really** want this to not happen, it should be configurable through a user option.

I'm switching this over to an enhancement.
