### ISSUE TITLE
Broken ssl P4PORT config 

### ISSUE THREAD

**Issue by ccarapencea** [groboclown/p4ic4idea#138]
I can no longer configure the ssl://host:4242 P4PORT in v.0.8.0
It is parsed as localhost:ssl and it complains about the non-numeric port number

**Comment by groboclown** [comment]
Thanks for the bug report.  This looks like an easy fix.   Should have a fix out in a few hours.

**Comment by groboclown** [comment]
This should be fixed in the new release that's out now.

**Comment by colinbgood** [comment]
2018.3 windows works, but OSX 2018.3 does not. I set ssl:<myserver>:1666 and the output adds "//" when it shouldn't. :(
"Could not Connect to Server: Unknown server sll://<myserver>:1666"

**Comment by groboclown** [comment]
The server string is parsed in [P4ServerName](../blob/master/idea-p4server/api/src/main/java/net/groboclown/p4/server/api/P4ServerName.java).  The separator "://" is added after parsing the protocol, hostname, and port from the input string.  However, for display syntax, the `getDisplayName()` should be showing only the `host:port` or `ssl:host:port` syntax.  Unfortunately, you're seeing a bug in the event notification that's showing one of the internal names, not the user-friendly name.

For background, the connection to the servier is handled in [SimpleConnectionManager](../blob/master/idea-p4server/impl/src/main/java/net/groboclown/p4/server/impl/connection/impl/SimpleConnectionManager.java).  This uses the [P4 Java API](https://www.perforce.com/perforce/doc.current/manuals/p4java-javadoc/index.html) to connect to the server using the specialized P4 Java url syntax.

Can you look at the IDE log and attach the associated stack trace?  It should be shown with the `UserErrorComponent` part, but this kind of low level error generally shows itself many times in the log.

**Comment by groboclown** [comment]
Closing this issue off after over a year with no feedback.
