### ISSUE TITLE
Invalid client name error

### ISSUE THREAD

**Issue by MalcolmEvershed** [groboclown/p4ic4idea#151]
When I startup Android Studio, I get this dialog:

> Check Connection
> 
> Problem with Perforce configuration: Invalid client name: MYCLIENTNAME
> Do you want to open the project settings to fix it? Selecting "No" will cause you to work offline.
> 
> Yes / No

My Perforce server log:

> Perforce server info:
> 	2017/06/22 16:27:07 pid 7796 myUserName@MYCLIENTNAME server [intellij-perforce-community-plugin-connection/0.9.2] 'user-info'
> Perforce server info:
> 	2017/06/22 16:27:07 pid 7796 myUserName@MYCLIENTNAME server [intellij-perforce-community-plugin-connection/0.9.2] 'user-clients -m1'
> Perforce server info:
> 	2017/06/22 16:27:07 pid 7796 myUserName@MYCLIENTNAME server [intellij-perforce-community-plugin-connection/0.9.2] 'user-info'
> Perforce server info:
> 	2017/06/22 16:27:07 pid 7796 myUserName@MYCLIENTNAME server [intellij-perforce-community-plugin-connection/0.9.2] 'user-clients -m1'
> Perforce server info:
> 	2017/06/22 16:27:07 pid 7796 myUserName@MYCLIENTNAME server [intellij-perforce-community-plugin-connection/0.9.2] 'user-info'
> Perforce server info:
> 	2017/06/22 16:27:07 pid 7796 myUserName@MYCLIENTNAME server [intellij-perforce-community-plugin-connection/0.9.2] 'user-clients -m1'
> Perforce server info:
> 	2017/06/22 16:27:07 pid 7796 myUserName@MYCLIENTNAME server [intellij-perforce-community-plugin-connection/0.9.2] 'user-property -nP4.Swarm.URL -s1 -m1 -l'
> Perforce server info:
> 	2017/06/22 16:27:07 pid 7796 myUserName@MYCLIENTNAME server [intellij-perforce-community-plugin-connection/0.9.2] 'user-login -a -p'
> Perforce server info:
> 	2017/06/22 16:27:08 pid 7536 myUserName@MYCLIENTNAME server [intellij-perforce-community-plugin-connection/0.9.2] 'user-info'
> Perforce server info:
> 	2017/06/22 16:27:08 pid 7536 myUserName@MYCLIENTNAME server [intellij-perforce-community-plugin-connection/0.9.2] 'user-clients -m1'
> Perforce server info:
> 	2017/06/22 16:27:08 pid 7536 myUserName@MYCLIENTNAME server [intellij-perforce-community-plugin-connection/0.9.2] 'user-clients -umyUserName'
> Perforce server info:
> 	2017/06/22 16:27:09 pid 8732 myUserName@MYCLIENTNAME server [intellij-perforce-community-plugin-connection/0.9.2] 'user-info'
> Perforce server info:
> 	2017/06/22 16:27:09 pid 8732 myUserName@MYCLIENTNAME server [intellij-perforce-community-plugin-connection/0.9.2] 'user-clients -m1'
> Perforce server info:
> 	2017/06/22 16:27:09 pid 8732 myUserName@MYCLIENTNAME server [intellij-perforce-community-plugin-connection/0.9.2] 'user-info'
> Perforce server info:
> 	2017/06/22 16:27:09 pid 8732 myUserName@MYCLIENTNAME server [intellij-perforce-community-plugin-connection/0.9.2] 'user-clients -m1'
> Perforce server info:
> 	2017/06/22 16:27:09 pid 8732 myUserName@MYCLIENTNAME server [intellij-perforce-community-plugin-connection/0.9.2] 'user-info'
> Perforce server info:
> 	2017/06/22 16:27:09 pid 8732 myUserName@MYCLIENTNAME server [intellij-perforce-community-plugin-connection/0.9.2] 'user-clients -m1'
> Perforce server info:
> 	2017/06/22 16:27:09 pid 8732 myUserName@MYCLIENTNAME server [intellij-perforce-community-plugin-connection/0.9.2] 'user-property -nP4.Swarm.URL -s1 -m1 -l'
> Perforce server info:
> 	2017/06/22 16:27:09 pid 8732 myUserName@MYCLIENTNAME server [intellij-perforce-community-plugin-connection/0.9.2] 'user-login -a -p'
> Perforce server error:
> 	Date 2017/06/22 16:27:24:
> 	Pid 8732
> 	Operation: user-clients
> 	Operation 'user-clients' failed.
> 	Command user-login was unexpectedly interrupted by command user-clients
> Perforce server info:
> 	2017/06/22 16:27:09 pid 8732 myUserName@MYCLIENTNAME server [intellij-perforce-community-plugin-connection/0.9.2] 'user-login -a -p'
> --- exited on fatal server error

FWIW, my Perforce config is to use `p4 set P4CONFIG=<custom file name>` and then in `<custom file name>`, I set P4CLIENT/P4IGNORE/P4PORT/P4USER. I can never get p4ic4idea to use this, so in the plugin settings window I use "Property Values" and "Client Name" to try to set it all manually. But today that did not work with 0.9.2.

**Comment by groboclown** [comment]
The plugin's reading of the "p4 set" values should be working better since the 0.9.0 release, but it still encounters issues.

This bug here appears to be an issue with the property configuration code.  For some reason, the password prompt isn't showing up.  I need to dig in further here.

**Comment by groboclown** [comment]
I think I have a solution for this. It looks like this came from an attempt to fix the problem where the plugin would ask many times for the password, but now the password just isn't being asked for at all.

**Comment by groboclown** [comment]
This should be fixed in the new 0.9.3 release.

**Comment by MalcolmEvershed** [comment]
Thanks, 0.9.3 worked for me.

"Specific Configuration File" also seems to work too, cool. (Though Relative File doesn't seem to allow the filename to be changed, but that is not blocking for me.)
