### ISSUE TITLE
Loosing connection to Perforce server

### ISSUE THREAD

**Issue by hakjac** [groboclown/p4ic4idea#154]
After update to 0.9.2 I loose connection to the Perforce server all the time. The "P4 Connected" icon in the lower right corner is green. But as soon as I try to edit a file it changes and indicates lost connection.

I have set up the P4 Connection using "property values", "client name" and "require a password".

Was forced to back to version 0.9.1 to be able to continue working.

**Comment by ronlv10** [comment]
+1

**Comment by groboclown** [comment]
I think I have a solution for this.  It looks like this came from an attempt to fix the problem where the plugin would ask many times for the password, but now the password just isn't being asked for at all.

**Comment by groboclown** [comment]
This should be fixed in the new 0.9.3 release.
