### ISSUE TITLE
Project tree disappears in Pycharm

### ISSUE THREAD

**Issue by Garoe** [groboclown/p4ic4idea#155]
In Pycharm 2017.1 on Ubuntu 16.04, the plugin installs and works fine. However, after clossing the project and opening it again, the folders in the project view are gone and it only shows external libraries. As a workaround changing the excluded or source folders in the settings makes the tree show again.

In the logs the only obvious error is
```
2017-07-05 10:41:17,025 [   7564]   INFO - er.connection.ServerConnection -  
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
	at java.util.concurrent.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:492)
	at java.util.concurrent.LinkedBlockingDeque.take(LinkedBlockingDeque.java:680)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerConnection.pullNextAction(ServerConnection.java:472)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerConnection.access$1400(ServerConnection.java:55)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerConnection$QueueRunner.run(ServerConnection.java:508)
	at java.lang.Thread.run(Thread.java:745)
```

If tested with java from two versions, and both with the same results. OpenJDK 1.8  and 1.9.

**Comment by groboclown** [comment]
Does disabling the plugin make the tree reappear?

**Comment by Garoe** [comment]
Yes, it does.

**Comment by groboclown** [comment]
Thanks.  I'll look into this and see what I can find.  I've seen this behavior with the gradle plugin when Idea rescans the project.  However, I'm not sure where this could come from.  This will take some digging.

**Comment by Garoe** [comment]
Looking a bit at the code, pycharm 2017 is on version 171 and the last branch of p4ic4idea is 163. Would that have something to do with it?

**Comment by groboclown** [comment]
The plugin compiles against multiple versions of the IntelliJ jars for compatibility reasons.  It uses the standard API where possible, which the 163 version supports.  Additionally, I don't see this with the Android or IntelliJ IDEs.

I'm testing it now with PyCharm to see if I can reproduce the problem on that platform.

**Comment by groboclown** [comment]
I was able to reproduce this in two test projects, loaded in the same session.  It's an interesting issue.  Here's some of the behaviors I found:

1. When this behavior was encountered, I changed one project's VCS to be "<none>".  After applying this (did not restart the IDE), the project list remained in the same state.
1. When I disabled the plugin and restarted the IDE, the full project list appeared.
1. When I re-enabled the plugin and restarted, the project with VCS set to "<none>" showed the project list correctly, while the project with VCS set to the Perforce plugin did not show the list.
1. When I changed the project's VCS from "<none>" back to the Perforce plugin, the project list was still present.
1. When I changed the project's VCS to "<none>" and closed / reopened just the project, the project's file list appeared correctly.

So the behavior seems to be related to the VCS setting when the IDE first loads the project.  Now that I have this behavior a bit more pinned down, I can see where the startup requests are causing the failure.  I think it has to do with timing around an initial request to get the Perforce server connection when there are no connections.

**Comment by Garoe** [comment]
Thanks for looking it this. That is pretty much the behaviour that I've been getting.

**Comment by hakjac** [comment]
After upgrade from 0.9.1. to 0.9.3 I experience this problem in IntelliJ. Disabling plugin and setting VCS to <none> makes the project tree appear. Enabling plugin and setting VCS to <Perforce> makes the project tree disappear again.

Downgrading to 0.9.1 solved the problem.

**Comment by groboclown** [comment]
Thanks, @hakjac.  That was the key that I needed.  I was able to identify the issue - it was a premature loading of the VCS roots before the project was loaded.  It looks like this caused a file system scan without the project, which mis-identified folders as not being part of the project.

I should have a release out soon.
