### ISSUE TITLE
P4InvalidConfigException: No client for file:///<file path>

### ISSUE THREAD

**Issue by CousinIt** [groboclown/p4ic4idea#159]
I've tried two systems (Win 10, Linux), both running AS 2.3.3, both with p4ic 0.9.5, both with similar config trying to access an existing workspace sync'd successfully from P4 at the command line. At the command line the config is simply P4PORT, P4USER and P4CLIENT set in the environment, and P4 commands work ok. I've set the same (I think) config up in AS using the Connection Configuration Stack using entries for 'Client Name', 'Require a Password', and 'Property Values' and filled these out with the same values as in my environment. Finally, I select perforce as the VCS for the root of my project.

I get a dialog that prompts me for a P4 password (sometimes several times), and entries in the P4 context menu in the UI are accessible (not greyed out).

But, every command I try on any file produces the a 'P4InvalidConfigException: No client for file:///<file path>' exception in the log and a message in the Messages tab. Using an almost identical config via IntelliJ Ultimate edition with built-in perforce support works, but I need to use AS as my project contains NDK elements for which AS+p4ic would be very useful.

**Comment by groboclown** [comment]
Unfortunately, the multiple password prompt is a long standing issue that hasn't had a good solution yet.  If you use `p4 login` from the command line, then you should look into using the `P4TICKETS` setting.

I see the "No client for (some file)" message reported only when the plugin doesn't have a mapping between the Perforce workspace file and the IDE file.  This can happen if the plugin hasn't ever been able to connect to the server.

To help understand the connection settings as understood by the plugin, click on the `Server Connection` tab in the Perforce settings dialog.

Let me know if you're still having trouble.

**Comment by CousinIt** [comment]
Hi, thanks for your advice. In fact I was not familiar with the P4TICKET setting having always previously provided a password to IntelliJ. So, I ran 'p4 tickets' at the command line and amended the p4ic settings to specify a P4TICKET value (which resulted in a file named after the ticket being placed in the project root folder), and removed the 'Require a password' setting.

At first this didn't seem to make any difference, so I started playing with the Directory setting on the main version control settings dialog, trying various levels of the directory hierarchy until I had it set to the top most directory under which the entire workspace is sync'd. This worked --- I was able to check out files, see them in the default change list, get annotations etc.). I then tried the refresh item from the context menu on the version control tab --- and the changelist details disappeared. Subsequently closing and reopening the project in AS leave me back with the same 'No client' message as before though the config hasn't changed.

So --- very puzzled. The config appeared to work, but stopped. Is there any way I can get any additional logging that would help nail this down?

**Comment by groboclown** [comment]
Try these debug values.  I assume you're familiar with adding in debug lines to the *Help* -> *Debug Log Settings* UI.

* `#net.groboclown.idea.p4ic.v2.server.connection.ServerConnectionManager` - Maintains a list of active connections, protects access to the active connections, and handles connections going offline.
* `#net.groboclown.idea.p4ic.v2.changes.P4ChangeListMapping` - Keeps track of the IDE concept of a changelist, and how it maps to Perforce changelists.

These ones are if you think the issue is in how the plugin initially connects to the Perforce server:

* `#net.groboclown.idea.p4ic.v2.server.authentication.ServerAuthenticator` - Details the authentication steps made during the initial handshake with the server.
* `#net.groboclown.idea.p4ic.config.P4ProjectConfigStack` - This will show you how the project configuration is constructed.
* `#net.groboclown.idea.p4ic.v2.server.connection.ClientExec` - Reports the operations performed against the server.

**Comment by CousinIt** [comment]
Thanks. I'll be away for the next couple of weeks --- will give them a try when I get back.

**Comment by Reveur** [comment]
Hi,

I am facing the same issue. I used plugin version 7 earlier and am trying 9 right now. The connection settings I am using is environment properties from perforce and a client selection. The p4tickets has been generated by default and used in the properties. Still, my connection cannot find client for my files. One thing is, my workspace root is at C:. This seems to work for a setup in which workspace is inside C:/user/<username>. Does that seem the reason? How do I debug this?

**Comment by groboclown** [comment]
You can enable extra debugging through the **Help** -> **Debug Log Settings** menu.  If you add the line

```
#net.groboclown.idea.p4ic.v2.server.authentication.ServerAuthenticator
```

to the list, then the IDE log will report whether it tried to use an auth ticket file, and will print the path of the ticket file.

**Comment by Reveur** [comment]
`2018-04-19 16:25:15,593 [   7782]  DEBUG - entication.ServerAuthenticator - Trying authentication with existing auth ticket file C:\Users\njaya\p4tickets.txt 
2018-04-19 16:25:15,593 [   7782]  DEBUG - entication.ServerAuthenticator - Session is valid and we're logged in 
2018-04-19 16:25:15,609 [   7798]  DEBUG - entication.ServerAuthenticator - Trying authentication with existing auth ticket file C:\Users\njaya\p4tickets.txt 
2018-04-19 16:25:15,609 [   7798]  DEBUG - entication.ServerAuthenticator - Session is valid and we're logged in 
2018-04-19 16:25:15,609 [   7798]   INFO - swarm.SwarmConnectionComponent - Could not find Swarm Server for {P4TRUST=(no value), P4PASSWD=<no plaintext password>, P4PORT=<domain>:<port>, P4TICKETS=C:\Users\njaya\p4tickets.txt, P4USER=njaya, Server Fingerprint=(no value)} 
2018-04-19 16:25:15,609 [   7798]  DEBUG - entication.ServerAuthenticator - Trying authentication with existing auth ticket file C:\Users\njaya\p4tickets.txt 
2018-04-19 16:25:15,624 [   7813]  DEBUG - entication.ServerAuthenticator - Session is valid and we're logged in 
2018-04-19 16:25:15,906 [   8095]   INFO - e.state.ClientLocalServerState - Flushing local and server cached states for njaya_IN-Njaya-DT:indperforce:1666 
2018-04-19 16:25:15,906 [   8095]   WARN - .sync.WorkspaceServerCacheSync - No client root ([]) mapped under project VCS roots ([file://C:/swdepot/NPS/multiuser]) 
2018-04-19 16:25:15,906 [   8095]  DEBUG - entication.ServerAuthenticator - Trying authentication with existing auth ticket file C:\Users\njaya\p4tickets.txt 
2018-04-19 16:25:15,906 [   8095]  DEBUG - entication.ServerAuthenticator - Session is valid and we're logged in 
2018-04-19 16:25:15,937 [   8126]   INFO - CompilerWorkspaceConfiguration - Available processors: 8 
2018-04-19 16:25:15,937 [   8126]   WARN - .sync.WorkspaceServerCacheSync - No client root ([C:\]) mapped under project VCS roots ([file://C:/swdepot/<path>/<path>]) 
2018-04-19 16:25:15,952 [   8141]   INFO - server.connection.AlertManager - Critical error 
com.intellij.openapi.vcs.VcsException: Workspace not synchronized.`

This is what I can see in the logs. What could be causing a connect issue?

**Comment by Reveur** [comment]
All entries shown here under <> are valid references. 
The log: No client root ([C:\]) mapped under project VCS roots ([file://C:/swdepot/<path>/<path>] seems to be point to a mismatch between the two file location formats.  I am not sure where to check for this.

**Comment by groboclown** [comment]
The code around the client root is completely changed in the 0.10 release, as is the authentication that resulted in the weird password prompts.  Workspace sync may still be an issue (see #174).
