### ISSUE TITLE
TeamCity Integration

### ISSUE THREAD

**Issue by glaw** [groboclown/p4ic4idea#160]
IDEA Community Edition TeamCity integration does not work with this plugin.  Error messages include either of the following.   

Suitable build configurations with non-manual VCS checkout mode in which you have permissions to start the builds were not found for the specified changes.

Failed to collect suitable build configurations: Argument for @NotNull parameter 'fullPaths' of jetbrains/buildServer/BuildServerManager.getSuitableConfigurationIds must not be null 

Is it possible to get this to work with teamcity integration?

**Comment by glaw** [comment]
I heard back from Jetbrains that the TC plugin for IDEA depends on specific classes provided by the JetBrains Perforce integration.   The list of VCS integrations the TC plugin works with is basically hard coded. Unfortunately, I think without some cooperation by jetbrains this can't be resolved.

**Comment by groboclown** [comment]
Thanks for looking into this.  I did some poking around in the community edition code but didn't come up with anything, either.
