### ISSUE TITLE
Error:Client '<client-name>' can only be used from host '<hostname>'. (error code 6239: severity 3, ref 6-95)

### ISSUE THREAD

**Issue by robbinalexander** [groboclown/p4ic4idea#162]
I have the client, require password and properties configurations in the connection configuration stack under Connection properties.
The client was created using the p4 client command from terminal.
Under properties, I have the p4port, p4user and p4host. 

I am able to login and can view file history, but when I try checking out a file, by running P4 -> Add/Edit, or just by trying to edit the file directly, get the error about the client not being usable here. I am able to edit, submit and other commands from the mac terminal.

**Comment by groboclown** [comment]
This means that the plugin does not identify the client's hostname the same way that the p4 workspace `Host` field is listed.  Usually, this is a case sensitivity issue (e.g. `Host` is all uppercase, while plugin finds it as all lowercase).

To fix this, you can either change the `Host` field in the workspace, or set the `P4HOST` configuration value.  See #136 and #61.

**Comment by robbinalexander** [comment]
That didn't help. Here's my config:

```
$ p4 info
User name: robbin.alexander
Client name: Robbins-MacBook-Pro_robbin.alexander_test
Client host: Robbins-MacBook-Pro.local
Client root: /Users/robbin.alexander/work/p4
Server address: p4.video54.local:1666
```


In Idea:
```
Client: Robbins-MacBook-Pro_robbin.alexander_test
P4PORT: p4.video54.local:1666
P4USER: robbin.alexander
P4HOST: p4.video54.local
```

`Output of java.net.InetAddress.getLocalHost().getHostName() - Robbins-MacBook-Pro.local`

Error while checking out - Error:Client 'Robbins-MacBook-Pro_robbin.alexander_test' can only be used from host 'Robbins-MacBook-Pro.local'. (error code 6239: severity 3, ref 6-95)

**Comment by groboclown** [comment]
`P4HOST` should be used if the auto-detection of the local hostname isn't working right.  In this case, try setting it to reference *your* computer name (`Robbins-MacBook-Pro.local`), and also double check the that the `Host` field in your client matches that `P4HOST` value.

**Comment by robbinalexander** [comment]
Not sure how setting P4HOST to localhost will help. The p4 server is running on a remote machine.
And I don't see any Host field in the client, see screenshot of IDE settings.
<img width="861" alt="screen shot 2017-09-10 at 9 24 13 am" src="https://user-images.githubusercontent.com/9024102/30249450-8d772330-965a-11e7-8443-8ca66d0e45cb.png">

**Comment by groboclown** [comment]
[P4HOST](https://www.perforce.com/perforce/doc.051/manuals/p4guide/ab_envvars.html) should not be "localhost" or the Perforce server host name, but rather the hostname of your computer as you see it in your client workspace.  This is how Perforce does some limited protection, to prevent the same client from being used on multiple computers (which can lead to bad things).

For example, if you run:

```
$ p4 client -o | grep "Host:"
Host:  Robbins-MacBook-Pro.local
```
Then your `P4HOST` value should be set to `Robbins-MacBook-Pro.local`

**Comment by robbinalexander** [comment]
That worked, thank you!
I think the parameter "P4HOST" is misleading. Can you consider renaming it to P4CLIENTHOST, since it's coming from "p4 client|grep host", or maybe document it to call it out?

Thanks again, you are doing an awesome job!

**Comment by groboclown** [comment]
Thanks for the encouragement.

I've updated the form so it includes tool tips to better describe each field.  I won't change the names, because I want to keep the names of the fields the same as what Perforce documents:

https://www.perforce.com/perforce/doc.current/manuals/cmdref/Content/CmdRef/envars.html
