### ISSUE TITLE
Plugin never asks for password

### ISSUE THREAD

**Issue by samaursa** [groboclown/p4ic4idea#166]
**Version:** PyCharm Community Edition 2017.2.4

**Error that I receive:**
Error:Problem editing files: [D:\av1\av1_dev\cdc\bin\maya\python\maya_setup\main.py] (Perforce password (%'P4PASSWD'%) invalid or unset.)

Seems to the same issue #80 . I have added the **Require a Password** to the configuration stack (I tried various positions in the stack with the same result).

**Comment by groboclown** [comment]
This sounds like a silly question, but do you get prompted for a password after IDE restart?  It's still a bug, but I'm wondering if that can get you past it momentarily.

**Comment by samaursa** [comment]
Good question! Sadly, I do not :(

**Comment by groboclown** [comment]
This is going to remain an issue in the v2 branch.  The v3 branch doesn't seem to have this issue.

**Comment by groboclown** [comment]
Closing off v0.9 bugs.  There is no expectation to support v0.9 in the future.
