### ISSUE TITLE
 Failed to change read-only status when using "import+" stream mapping

### ISSUE THREAD

**Issue by zwadar** [groboclown/p4ic4idea#167]
Hello,
I have main p4 stream mapped to root of a hard drive. e.g P:\ . Then I have another stream with tools and I'm importing it to the main stream via "import+" to sub-folder P:\tools .
Although using P4V checking out and general perforce interaction works well, I can't checkout the files in P:\tools folder from PyCharm. The plugin errors with message

Failed to change read-only status for the following files: P:\Tools\<name_of_the_file>

**Comment by groboclown** [comment]
The plugin has two modes for checking out files - immediate and background (on the User Preferences panel in the Settings dialog, labeled "Open for edit in background").  The default mode (immediate) causes the plugin to run the "p4 edit" command and wait for the response before giving back control to the IDE.  In background mode, it will directly try to mark the file as writable, then spawn a background task to open the file for edit.

It sounds like you're using the default mode.  If something went wrong with the "p4 edit" command, then the PyCharm log file should contain the stack trace pointing to the source of the problem.  Can you check the log to see if it reports the underlying problem?

**Comment by groboclown** [comment]
Closing old issues due to over a year without feedback.
