### ISSUE TITLE
Can't checkout files above the project folder. 

### ISSUE THREAD

**Issue by pyroxiano** [groboclown/p4ic4idea#170]
Hi. I'm using Android Studio on Windows, and compile multiple apps on multiple platforms, so my NDK Android app's folder structure looks something like this:

`C:/Code/MyApp/Projects/Android_Studio` (Android Studio project - contains build.gradle etc.)
`C:/Code/Common` (Shared code between platforms goes here)
`C:/Code/Platform/Android` (Android platform specific code goes here)

I've set the correct values for user, port, tickets and client in Connection Properties

My Perforce workspace root is set to "C:/Code", so I've added "C:/Code" as a Directory (in Version Control) and set its VCS to Perforce.

I've also removed the default <Project> folder that appears there, but in the Server Connection tab, the "Root dir:" drop-down contains both "C:/Code" and "C:/Code/MyApp/Projects/Android_Studio" (Which should have been removed?)

Selecting "C:/Code/MyApp/Projects/Android_Studio" shows "Other root directories have problems."
Selecting "C:/Code" shows "Invalid "port" connection string value: null" and "Missing username definition", despite those values being set in the Connection properties. P4PORT and P4USER both display as (no value) in the 'Resolved Configurations' window

Attempting to edit a file under the C:/Code workspace, results in a "Failed to change read-only status for the following files:" error.

This occurs for both files under the project folder (e.g. C:/Code/MyApp/Projects/Android_Studio/app/build.gradle) and files under the Perforce workspace root (e.g. C:/Code/Common/Timers.cpp)

Have I missed something, or is this a bug?

**Comment by TheAndrewStevens** [comment]
I have a similar setup and have been experiencing similar issues for a while. I used to have it working in a previous version of the plugin (can't remember which) by specifying a p4 configuration file in C:/Code under the Connection Properties tab (which contains P4PORT, P4HOST, P4USER, P4PASSWD, P4CLIENT vars). This fixed the error messages for me so you could try that. 
Unfortunately now like you I've got the two paths in the Root dir drop down under Server Connection tab and am unable to select the directory (C:/Code in your case) above the project directory without it defaulting back to the project directory. Trying to edit a file with this setup doesn't provide an error message but does make the file writable without checking it out - quite dangerous!
Like I said this setup was working in previous versions, please fix!

**Comment by groboclown** [comment]
This was a limitation with the way the plugin managed searching for relative configuration files.  The new 0.10 version that's under development changes how this is handled - now the plugin manages your connections based on a VCS root.  In the  examples above, you would use the IDE VCS settings for each root directory (`C:/Code/MyApp/Projects/Android_Studio`, `C:/Code/Common`, `C:/Code/Platform/Android`), and setup up the connection properties for each one.  This makes for a bit more work, but is more reliable than the old method.

https://github.com/groboclown/p4ic4idea/releases/tag/0.10.0-alpha-1

Please note the caveats that are noted throughout that release.  I personally have been able to switch to the new alpha plugin, work with it a while, and switch back to the 0.9 versions, but don't expect settings to be preserved when switching back and forth.

**Comment by TheAndrewStevens** [comment]
Great, thanks! I haven't been able to get more than one Active Connection to appear under the new Version Control tab, but if I just use the highest level directory (C:/Code) it seems to work just fine.

**Comment by groboclown** [comment]
The plugin bases the view on the list of VCS roots.

![image](https://user-images.githubusercontent.com/6464033/42176902-30c3455a-7df0-11e8-840b-b7dd4ffd0061.png)


![p4ic-connections](https://user-images.githubusercontent.com/6464033/42176339-407509c2-7dee-11e8-91f0-c62b3a20bbd6.png)

There's a memory issue with the active connection panel that I've been working through.

**Comment by groboclown** [comment]
The next alpha release is available.  It improves upon the previous one with reverts, history, annotations, and diff support.

https://github.com/groboclown/p4ic4idea/releases/tag/0.10.0-alpha-2

**Comment by groboclown** [comment]
This was tackled as part of the 0.10 release.
