### ISSUE TITLE
temporary file folder issues with windows

### ISSUE THREAD

**Issue by scriptacus** [groboclown/p4ic4idea#172]
The plugin caches the name of a temporary folder for temp file storage; windows will sometimes delete this folder if it happens to be empty (it is most of the time) which can lead to errors with the plugin.

**Comment by groboclown** [comment]
Thanks for the bug report.  I've seen some of these related issues, but you were able to track down the source of the missing directory.  Some aspects of this issue have been addressed in then new 0.10 code base, but I'll look into adding more checks before server connections.

**Comment by groboclown** [comment]
As far as I can tell, the temp folder is checked for existence before being used now.
