### ISSUE TITLE
plugin changing file type

### ISSUE THREAD

**Issue by scriptacus** [groboclown/p4ic4idea#179]
There's a .txt file in my project that appears to be getting it's perforce type changed from utf16 to text.  I think maybe this only happens when it's the plugin that checks the file out.  If it's checked out externally and than edited in IntelliJ the type remains correct.

**Comment by groboclown** [comment]
Thanks for the bug report.  It looks like the detection of the file type was just assuming text if the IDE didn't report it as binary.  For adding files, I'm changing it to let the Perforce server decide the best type mapping, rather than forcing an assumed type.

**Comment by groboclown** [comment]
This fix is in the 0.10.0-Alpha 8 release.
