### ISSUE TITLE
Instead of using default changelist, new changelist is created

### ISSUE THREAD

**Issue by hkalina** [groboclown/p4ic4idea#216]
**Describe the bug**
When I try to use default P4 changelist (changelist 0), P4 idea  plugin creates new changelist called "Default Changelist"

**To Reproduce**
1. Click on file - P4 - Open for add/edit
2. In Perforce panel move the file from active changelist into "Default Changelist"
3. Now Idea has created new regular changelist called "Default Changelist" and moved the file into it - in Perforce panel are now TWO changelists called "Default Changelist"
4. When checking in P4V, there are two changelists - "default" and regular changelist called "Default Changelist"

**Expected behavior**
File should appear in changelist "default" in P4V and under Default Changelist in Idea.

**Attachments**
![screen-p4-idea](https://user-images.githubusercontent.com/3178122/81561953-547ad380-9394-11ea-99a8-fd20f8ff092b.png)

**Desktop (please complete the following information):**
 - OS: Fedora Linux
 - IDE and version: IntelliJ 2020.1.1
 - Version 0.10.16

**Comment by groboclown** [comment]
There are long-standing issues with the internals of the plugin with the way it maps Perforce changelists to the IDE's changelists.  I'm working through the issues, but it's complicated.

**Comment by groboclown** [comment]
This might be related to #213, strangely enough.  I have a fix for that one coming out soon.

**Comment by hkalina** [comment]
@groboclown confirmed - this is fixed in 0.10.17 :+1:
