### ISSUE TITLE
non-numeric perforce server port

### ISSUE THREAD

**Issue by wilyApps** [groboclown/p4ic4idea#23]
Hello, I'm unable to use Your plugin because of this message when I'm trying to check connection: http://screenshot.cz/ZNOHJ/
-port is OK  (1666), but the error message says it's wrong, i guess the problem is because of dots in server ip, thanks.

EDIT: the problem was in my p4config file, there was a blank space after my port, so not "1666", but "1666 ". But there is still another problem whether if I try to check connection via cfg file or with just typing port and username, it will always stuck, no pop up window is shown, img: http://screenshot.cz/KN8ZC/ - I was waiting several minutes but nothing happened. Idea version: 14.0.3.Thanks for help.

EDIT2: see last comment, thanks.

**Comment by groboclown** [comment]
Thanks for the bug report.

For the first issue, I'll add in whitespace trimming to help keep this from happening in the future.

For the second one, if you see this happening again, could you attach your IDEA log?  You should be able to find it through the *Help* -> *Show Log in Explorer* menu (there shouldn't be sensitive information in there, but you may want to double check before attaching).

**Comment by wilyApps** [comment]
Hello, thx for reply. Here are the logs, leave message when you release the fix, have a nice day.
http://www.filedropper.com/20150309-192349

**Comment by wilyApps** [comment]
EDIT: the problem was I did not applied the selected p4config file before pressing "check connection" button, but still there is a problem to connect to server, if I press "check connection" it will throw these errors (the first is above and the second is below) -> http://screenshot.cz/OO535/. My p4config file contains: P4PORT=perforce.assembla.com:1666
P4HOST=xxx
P4USER=xxx
P4CLIENT=xx
P4CHARSET=utf8
-the fields with "xxx" property are in simple format (no spaces, no uppercase letters and no numbers), maybe there are problems with dots in server URL..

**Comment by groboclown** [comment]
Could you inspect the idea log file, and attach the stack trace to this issue?  I doubt that the error is with the dots in the host name; I use an IP address without issues.  The underlying issue ("server connection unexpectedly closed") could come from any number of problems.

One thing that might be interesting to look at would be if the application identifier that the client sends is being blocked.  Do you know if there is a p4 broker or similar proxy between your computer and the server?

**Comment by wilyApps** [comment]
I'm not sure but i don't think there is a blocker. I checked firewall and there was nothing suspect.
Here are the logs, they only appeared when I turned on idea and p4 plugin automatically wanted to create connection, but it did not work and i had to stay in offline mode.
http://www.filedropper.com/threaddumps-20150314-130917-ic-1391117

**Comment by groboclown** [comment]
Thanks for the stack trace.  Unfortunately, it only shows the state of the ide when it encountered a slowdown, and the p4 plugin wasn't active at that time.  Instead, can you look at the idea.log file?  You can find it by clicking on "Help" from the menu bar, then select the idea.log item.  That should contain lots of logging from the plugin about what it tried to do to log in.  Note, however, that usernames and p4 port information will be there, but passwords shouldn't be there.

**Comment by wilyApps** [comment]
http://pastebin.com/kmni4fT6 - here is the stack trace we are looking for. I also checked if it was caused by firewall but it was not. Thanks.

**Comment by groboclown** [comment]
Thank you very much for the log file!  This is what I feared - the underlying P4 api is receiving a disconnect from the Perforce server (or something in-between is forcing a disconnect), and the client just isn't reporting anything.  I'll look into what can be done to better understand the source of this problem.

Until I can dig deeper into this, my last recommendation is to recheck your credentials, that whichever authentication method you're using is valid for your server.

**Comment by wilyApps** [comment]
Thanks for the support :) btw I was checking around the settings in my p4 client, and i revealed that after I type "p4 info" into command line, and in the output there was "Server licence: none" property. May this be the problem ?

**Comment by groboclown** [comment]
That shouldn't give this kind of error.  I sometimes test out the plugin with a trial (license-free) server.  Do you know what version of the server you're connecting to?  It should be in that p4 info result.  I'll contact Perforce support and see if they have any feedback.

**Comment by wilyApps** [comment]
could you please contact me on orlickymario@gmail.com ? I don't want to post here all the results, thanks

**Comment by groboclown** [comment]
Due to lack of response, and no one else commenting on this issue as seeing the same thing, I'm going to close it off.  Feel free to open a new issue if you see this happening again, or re-open it (if Git allows you).
