### ISSUE TITLE
Add "get project from VCS" hook

### ISSUE THREAD

**Issue by groboclown** [groboclown/p4ic4idea#60]
The welcome screen quick start has the "WelcomeScreen.GetFromVcs" action (com.intellij.openapi.wm.impl.welcomeScreen.GetFromVcsAction).  This requires registering a CheckoutProvider with the plugin.

**Comment by Wavesonics** [comment]
+1 this would be a great feature

**Comment by groboclown** [comment]
In the 0.10 release.
