### ISSUE TITLE
Keeps refreshing local changes

### ISSUE THREAD

**Issue by umachana** [groboclown/p4ic4idea#67]
The local changes keep getting refreshed in the background ; almost every second. I changed the Settings>Version Control>Background "Refresh changes every" property to  30 minutes. But this background process keeps sending message to the perforce server. 

![image](https://cloud.githubusercontent.com/assets/13766533/9228028/882193a2-40e4-11e5-94c8-34a66ef4073a.png)

**Comment by umachana** [comment]
Seems to be fixed in the latest version.

**Comment by groboclown** [comment]
Thanks for the bug report.  The quick hotfix was explicitly there to fix this issue.
