### ISSUE TITLE
P4IGNORE environment variable not recognized

### ISSUE THREAD

**Issue by bveenvliet** [groboclown/p4ic4idea#69]
Set environment variable P4IGNORE=.gitignore
Add a file to the project that is not in source control yet but is present in the .gitignore
It will prompt you to add the file to source control even though it should be ignored.

This works properly in P4V when I reconcile offline changes, it does not prompt me to add files that are in the .gitignore list.

**Comment by groboclown** [comment]
Thanks for the report.  This is on my to-do list, but at the moment my priority is getting a bunch of fixes for the intelligence 15 release.  This should hopefully include support for the ignore files.

**Comment by groboclown** [comment]
Support for ignore files is now added for the 0.7 release.  Please let me know if you find problems with this.

On a side note, I tried to take care to replicate the behavior of P4V, which is that only files not already on the server are ignored, whereas editing files that are in the ignore list and already known by Perforce will still be opened for edit.
