### ISSUE TITLE
Copy/paste and cut/paste of files do not trigger P4 actions

### ISSUE THREAD

**Issue by RSFlux** [groboclown/p4ic4idea#71]
Copying a file to a new location and cut/pasting a file to a new location do not properly trigger adds/deletes. In the first case, an add dialog appears, but the file is never added to the P4 changelist. In the later case, the source file for the cut/paste is checked out instead of deleted, and the new file is never added.

p4ic4idea version 0.6.6.1
PyCharm version 4.5.4

**Comment by groboclown** [comment]
Thanks for the report.  I'm in the middle of a major refactoring of the server code, but I'll add this to the backlog of issues that I want to include in the next release.

**Comment by groboclown** [comment]
I'm testing out the fix for this with the beta version of the 0.7.0 release and PyCharm 5.0.

**Comment by groboclown** [comment]
There were some lingering issues, but I've fixed them now in the 0.7.0 branch.
