### ISSUE TITLE
Falsely reporting that JCE is not present on Windows 7

### ISSUE THREAD

**Issue by Wavesonics** [groboclown/p4ic4idea#72]
I'm running Windows 7, and I installed JCE 8 from Oracles website into:
`C:\Program Files\Java\jdk1.8.0_25\jre\lib\security`

I've even confirmed that it is present by running a little Java program using this to check:
```
unlimited = Cipher.getMaxAllowedKeyLength("RC5") >= 256;
System.out.println("Unlimited cryptography enabled: " + unlimited);
```
And this reports: `Unlimited cryptography enabled: true`

However, after installing `p4ic4idea` into Android Studio 1.4.1, and configuring my p4client, clicking `Check Connection` presents the following error:
```
Problem with Perforce configuration: Standard Java does not support the 256-bit encryption level ciphers required by the Perforce server.  You must download and install the unlimited strength JCE package for the IDE's JRE.

JRE version: 1.8.0_25
JRE vendor: Oracle Corporation
JRE vendor URL: http://java.oracle.com/
JRE location: C:\Program Files\Java\jdk1.8.0_25\jre
```

I've restarted both Android Studio and the whole computer to make sure it wasn't an issue with re-initializing Java or something.

Has anyone successfully used this plugin on this combination?
Windows 7
JDK 1.8
Android Studio 1.4

**Comment by groboclown** [comment]
This error report is actually caused when the `SSLSocket` session for the P4 server connection reports as invalid (`isValid()` returns `true`).  The usual reason for this is a lack of the unlimited cryptography strength files.

However, I've noticed that the same problem can occur when the client can't create a full connection to the server, such as when I'm connecting through a proxy, but the server is down.  Unfortunately, the underlying Perforce Java API can't tell the difference between an invalid encryption capability and a server that's disconnected.

Out of curiosity, is your server setup to use the Perforce secure server, or is it a real SSL tunnel?

**Comment by Wavesonics** [comment]
Hhmmm that sucks about the P4 API.

One minor improvement could be adding that line of code to check for the max key length, and at least have a more informative error message in this case. Basically detect on your side if it's a missing JCE error, or something else.

However, removing ssl from my P4PORT makes it work! (Wasn't completely sure about my P4 server setup)

Thanks for this plugin, this will really improve my workflow!

**Comment by groboclown** [comment]
Thanks for the support.

That's a good idea about checking the existing max key length.  I'll include that in the checks.
