### ISSUE TITLE
Repository History doesn't work

### ISSUE THREAD

**Issue by Wavesonics** [groboclown/p4ic4idea#73]
I'm not sure if this is a known bug or limitation, but currently, clicking the refresh button in the `Repository` tab does not work.

It brings up the `VCS History Cache Settings` dialog, but clicking `OK` does nothing.

This would be a useful feature to prevent you having still having to use P4's own UI for even more things.

**Comment by groboclown** [comment]
This is on the plugin's list of limitations, along with not indicating to the user whether a file is synchronized to the head revision or not, and no resolving merge conflicts.  I'll put this on the near future release schedule.

**Comment by Wavesonics** [comment]
So not currently supported, but possible via the API?

**Comment by groboclown** [comment]
Yes, the P4 java api makes this data available, but I have been putting my focus on other aspects of the plugin first.

**Comment by groboclown** [comment]
Finally have this working, in the 0.10 release line.
