### ISSUE TITLE
Error updating changes

### ISSUE THREAD

**Issue by Wavesonics** [groboclown/p4ic4idea#74]
I'm using the plugin in Android Studio 1.4.1, and things appear to be working, however, during builds I get errors in the Version Control window.

It's always about some untracked file, either a file inside the .idea directory, or something deeper the temp files produced by the build.

The specific error is:
`Error updating changes: C:[path to some file]`

It doesn't appear to be breaking anything at the moment though.

**Comment by groboclown** [comment]
Thanks for the bug report.  I'll see if I can reproduce this in the updated version of the plugin.

**Comment by groboclown** [comment]
I haven't been able to reproduce the problem using the latest version.  If you can, please try out the 0.7.0-rc3 release:

https://github.com/groboclown/p4ic4idea/releases/tag/v0.7.0-rc3

If you have problems with that version, you can reload the previous version (0.6.6.1) to get back to a working state.

**Comment by groboclown** [comment]
I haven't heard back on this issue, nor have I heard any related issues for the 0.7 release vehicle.  I'm going to close it off as fixed.  If you're still experiencing similar issues, please open a new ticket.
