### ISSUE TITLE
"Can't get revision content"

### ISSUE THREAD

**Issue by scriptacus** [groboclown/p4ic4idea#78]
Getting this error when trying to diff files from the Version Control "Local Changes" tab

**Comment by groboclown** [comment]
Thanks for the bug report.  I'll look into this issue.  I'm assuming that, based on upon your previous issue, that you're running with the 0.7.0-rc4 release.

**Comment by groboclown** [comment]
This ended up being a nasty little bug.  Thanks again for pointing it out.  I'll have the fix available in the 0.7.0-rc5 release.
