### ISSUE TITLE
Pycharm does not ask for p4 password in 0.7.0

### ISSUE THREAD

**Issue by murawskikrzysiek** [groboclown/p4ic4idea#80]
I was not able to use p4 connection with the 0.7.0. Was never asked for password.

**Comment by groboclown** [comment]
Thanks for the bug report.  I'll look into the issue to see if there is something obvious, but if you provide some basic details into information about your server connection and reported error would help me pin down the source.  Did the plugin tell you an error message?  Do you happen to know if your server requires an authentication ticket, or if a simple password is sufficient?

**Comment by groboclown** [comment]
There are definitely some issues around this area of the code.  The prompt about what you want to do will only clear out the password, and it pops up the same time as the password prompt.  Additionally, unselecting the "store password" checkbox will end up not using the password.

However, I haven't been able to reproduce this particular problem around the password prompt never appearing.  I'll try a few other angles to see where I can try to reproduce this.

**Comment by groboclown** [comment]
This is a definite issue in all the varieties of the editors.  I'm testing out a fix.
