### ISSUE TITLE
"Silently go offline on disconnect" causes repeated gone offline dialog prompts

### ISSUE THREAD

**Issue by zhouziyang** [groboclown/p4ic4idea#83]
i'm using Android Studio 1.5 with perforce plugin enabled. however, the changelist won't sync with p4v client when connect is broken or submit changelist by p4v. also, plugin is always show error message when connection is lost.  i have to restart Android Studio to make plugin work properly.

**Comment by groboclown** [comment]
Thanks for the bug report.  It sounds like you might be seeing several different issues.  I'll try to break them down to better understand what you're experiencing.  Please let me know if I misunderstood you.

1. *When the plugin fails to connect to the server, you see an error message.*  If this is a behavior that you're seeing, can you tell me if the "Silently go offline on disconnect" option is set in the options panel?  Do you see an error message repeatedly showing up for the one disconnect, or is it just once?
1. *When you submit a changelist with P4V, then attempt to refresh the changelist view, the plugin loses the connection to the server.*  Do you see an error message when this occurs?  If so, could you post the contents?
1. *When the plugin is disconnected from the server, the changelist won't reload the server state.*  If the plugin is working in offline mode, then you'll need to manually reconnect to the server.  You can do this through several ways - click on the P4 widget on the bottom status bar; select the menu VCS -> P4 -> Work online; through the VCS popup menu (Alt-back tick in Windows); and through the project view context menu P4 -> Work online.

I interpreted "sync" to mean "load the status of the files and changelists"; if you mean an actual `p4 sync` operation (download files from the server), then the behavior for offline mode should be the same.

Again, please let me know if I misunderstood the errors you were seeing.

**Comment by zhouziyang** [comment]
Regarding to you comments,

1. Yes, i checked "Silently go offline on disconnect" option. after unchecked, the connection seems work fine (will prompt for credentials). if option checked and connection is broken, error message will repeatedly showing up (and change focus to message panel).

2. After uncheck "Silently go offline on disconnect", no such connection issues.

3. The connection is fine. But the changelist state is not synced with p4v (plugin will automatically checkout files when edited, and changelist is submit by p4v). changelist will show "No files" after clicking "Synchronize <Project-Name>" in project context menu, but the changelist state is back after clicking Refresh button in Version Control panel. plugin will leave checked out files (automatically when edited) in changelist even after submitted by p4v. Maybe it's a bad practice to submit changelist by p4v, I should submit in plugin.

**Comment by groboclown** [comment]
(1) and (2) - thanks for the clarification.  I haven't been looking at that area of the code in a while; looks like there's an issue around the dialog display.

(3) The "synchronize" button isn't connected to the changelist refresh, which is the IDE integration point the plugin uses to fetch file checkout information.  I'll open this as a separate issue to keep the bug tracking kind-of sane.

Thanks for the clarifications!

**Comment by groboclown** [comment]
This is probably related to #90.  I have a plan of attack on how to tackle this issue, so hopefully it won't be too long before there's a fix.

**Comment by groboclown** [comment]
The synchronize issue was the same as #90, but the working offline repeated dialog issue is not reported elsewhere, so I'm changing this issue title to reflect that problem.
