### ISSUE TITLE
changelist view out of sync

### ISSUE THREAD

**Issue by scriptacus** [groboclown/p4ic4idea#90]
My "Local Changes" tab shows many changelists that no longer exist.  I suspect this is a caching issue that is caused by removing a changelist from another program (like P4V).  It's possible that this will be fixed with implementation of the "Refresh" functionality.

**Comment by groboclown** [comment]
Thanks.  I've started seeing a few of these issues as well, in particular related to the revert operation.  I think the current code base is too conservative in regards to flushing out the cache.  I have some ideas that should help improve this.
