### ISSUE TITLE
Perforce Plugin ignoring settings from .p4enviro file

### ISSUE THREAD

**Issue by walker5209** [groboclown/p4ic4idea#94]
Perforce settings from ~/.p4enviro are ignored and only honored if they are copied into .p4config file.

.p4enviro settings such as P4USER/P4PASSWD/P4PORT/P4EDITOR/P4HOST/P4MERGE/P4DIFF should be used and then overwritten with any specific settings in the .p4config

**Comment by groboclown** [comment]
Implementation note: this should use the PerforceEnvironment.getP4Enviro() call to ensure that it uses the default value if not set.

**Comment by groboclown** [comment]
I'm working now on allowing for a list of configurations, so that you can have, say, 2 config files and 1 override.  You'll then be able to have your p4 enviro file as the bottom file, and the p4 config file above that.

**Comment by groboclown** [comment]
Fixed in 0.8.0
