### ISSUE TITLE
Performance issues seen with keypress events

### ISSUE THREAD

**Issue by groboclown** [groboclown/p4ic4idea#99]
On some installs, the plugin can cause severe lag on each key press within the editor, regardless of whether the plugin is working in online or offline mode.

The editor is probably sending open for edit requests with each key.  Several parts of the code may be slowing it down.

**Comment by groboclown** [comment]
This will be a new "User Preference" option that will put the open for edit request into a background thread, and in the case where the file actually should be open for edit, the code will still mark the file as writeable first.

**Comment by groboclown** [comment]
This should hopefully be fixed when the user preference option is selected.

**Comment by timmikk** [comment]
I started using this plugin some weeks ago. When plugin is online the lag makes Idea unusable. It takes many seconds for written text to appear on screen. Also many other operations seems to be very slow. The same problem exists even after the new background thread option is enabled. Only solution I have found is to put the plugin in offline mode.

**Comment by groboclown** [comment]
I haven't heard of anyone else experiencing this situation.  Do you have some specifics about your configuration that I can use to help better understand where the performance bottleneck is happening?

**Comment by groboclown** [comment]
Some things that might help include:
* Which JetBrains IDE and version are you using?
* Which OS are you running on?
* Are you using the default IDE JRE to run the IDE, or are you using a custom one?

**Comment by timmikk** [comment]
My environment:
IntelliJ IDEA 14.0.3 -- Build #IC-143.1821
I'm using the default JRE: 1.8.0_45-b15 amd64
Running on Windows 7 SP1

I have two suspections for the cause:

1. The plugin cannot handle very large projects with tens of modules. I have not yet tried it out with smaller project.


2. There is something wrong with my Perforce connection configuration. I'm using the "Client Password" connection type and don't use any environment variables. Still at the bottom text area it says "(invalid configuration)" see the screenshot:

![image](https://cloud.githubusercontent.com/assets/7206719/12881169/3bd2ed62-ce50-11e5-9e55-cd80c76396ac.png)

**Comment by timmikk** [comment]
I tried with smaller project and everything was working relatively well for couple of hours. Then I imported more project modules, well in matter of fact about twenty but removed most of them and only four was left. After this the freezing started. So the project size might have effect but may not explain everything.

I have been running the VisualVM profiler on second monitor. I have feeling that every time the Idea got stuck the Change List Updater thread was running. The moment the updater thread stopped running the Idea screen refreshed and did what ever I tried to do while it was in freeze.

**Comment by groboclown** [comment]
Thanks for investigating this.  I was looking into the change list updater, too, as that's the one part that can't be forked off into a background thread.  From what I can see, the most serious performance issue with this is when Idea detects a file as having been changed, but there hasn't been any changes.  Right now, the plugin does a diff against the server version to see if it really has been changed without being opened for edit.  Up to this point, I've only seen Idea report only a few files as being in this state, but I have a feeling that your particular configuration is putting many files in this state.

I am working on putting a cached MD5 of the server files to make the checking faster.

**Comment by groboclown** [comment]
Let me know if the latest release fixed this issue for you.  Additionally, if the "md5" solution alone wasn't enough, you can try disabling the comparison altogether through the User Preferences.

**Comment by groboclown** [comment]
I'm going to close this issue off, as I haven't heard back on how the new functionality is working for you.  Please re-open this ticket or create a new one if you continue to see this problem.
